version: "3.8"
services:

  rabbit:
    image: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  eureka:
    image: alexvaitsekhovich/ordering-eureka-server
    ports:
      - 8761:8761

  config-server:
    image: alexvaitsekhovich/ordering-config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'

  failover-service:
    image: alexvaitsekhovich/ordering-failover
    ports:
      - 8093:8093
    depends_on:
      - eureka
      - config-server
      - zipkin
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_ZIPKIN_BASEURL: http://zipkin
    restart: on-failure

  order-api:
    image: alexvaitsekhovich/order-api
    ports:
      - 8080:8080
    depends_on:
      - eureka
      - config-server
      - rabbit
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure

  gateway:
    image: alexvaitsekhovich/ordering-gateway
    ports:
      - 9090:9090
    depends_on:
      - eureka
      - config-server
      - failover-service
      - order-api
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure




